import 'package:get/get_navigation/src/root/internacionalization.dart';

class LanguageClass extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Chat with Astrologer": "Chat with Astrologer",
          "Call with Astrologer": "Call with Astrologer",
          "Share": "Share",
          "Talk to Astrologer": "Talk to Astrologer",
          "Chat Astrologer": "Chat Astrologer",
          "Call Astrologer": "Call Astrologer",
          "Directory of Astro": "Directory of Astro",
          "Horoscope": "Horoscope",
          "Kundli": "Kundli",
          "Free Services": "Free Services",
          "User Review": "User Review",
          "Wallet": "Wallet",
          "See All": "See All",
          "My Orders": "My Orders",
          "Blogs": "Blogs",
          "Recharge History": "Recharge History",
          "Following": "Following",
          "Refer and Earn": "Refer and Earn",
          "Directory": "Directory",
          "Help & Support": "Help & Support",
          "FAQ's": "FAQ's",
          "Register as Astrologer": "Register as Astrologer",
          "Amount": "Amount",
          "Proceed to Pay": "Proceed to Pay",
          "Subtotal": "Subtotal",
          "Total": "Total",
          "Payment Successful": "Payment Successful",
          "Wallet Balance": "Wallet Balance",
          "Aries": "Aries",
          "Taurus": "Taurus",
          "Gemini": "Gemini",
          "Cancer": "Cancer",
          "Leo": "Leo",
          "Virgo": "Virgo",
          "Libra": "Libra",
          "Scorpio": "Scorpio",
          "Sagittarius": "Sagittarius",
          "Capricorn": "Capricorn",
          "Aquarius": "Aquarius",
          "Pisces": "Pisces",
          "Matchmaking": "Matchmaking",
          "Panchang": "Panchang",
          "Gallery": "Gallery",
          "Reviews": "Reviews",
          "Astrologer Profile": "Astrologer Profile",
          "Availability Time": "Availability Time",
          "Coupon": "Coupon",
          "Completed": "Completed",
          "All": "All",
          "Ongoing": "Ongoing",
          "Consult": "Consult",
          "Time": "Time",
          "Duration": "Duration",
          "Charge": "Charge",
          "Total Charge": "Total Charge",
          "Follow": "Follow",
          "Total balance": "Total balance",
          "Recharge now": "Recharge now",
          "Wallet Transactions": "Wallet Transactions",
          "Payment Logs": "Payment Logs",
          "Invoice": "Invoice",
          "Chat with \"Astrologer_Name\" for 10 mins":
              "Chat with \"Astrologer_Name\" for 10 mins",
          "Call with \"Astrologer_Name\" for 10 mins":
              "Call with \"Astrologer_Name\" for 10 mins",
          "Failed": "Failed",
          "Successful": "Successful",
          "Recharge": "Recharge",
          "Transaction ID": "Transaction ID",
          "Hindi": "Hindi",
          "Tamil": "Tamil",
          "Register yourself in Hello Astrologer Directory":
              "Register yourself in Hello Astrologer Directory",
          "Click here": "Click here",
          "About Us": "About Us",
          "privacy policy": "privacy policy",
          "Terms & Conditions": "Terms & Conditions",
          "Log Out": "log out",
          "Chat": "Chat",
          "Call": "Call",
          "Home": "Home",
          "Settings": "Settings",
          "Have doubts?": "Have doubts?",
          "Balance": "Balance",
        },
        "hi_IN": {
          "Chat with Astrologer": "ज्योतिषी के साथ चैट",
          "Call with Astrologer": "ज्योतिषी के साथ कॉल",
          "Chat Astrologer": "ज्योतिषी से चैट",
          "Call Astrologer": "ज्योतिषी से कॉल",
          "Talk to Astrologer": "ज्योतिषी के साथ कॉल",
          "Horoscope": "राशिफल",
          "Kundli": "कुंडली",
          "Free Services": "मुफ्त सेवाएं",
          "User Review": "उपयोगकर्ता समीक्षा",
          "Wallet": "वॉलेट",
          "See All": "सभी देखें",
          "My Orders": "मेरे आर्डर",
          "Blogs": "ब्लॉग",
          "Recharge History": "रिचार्ज हिस्ट्री",
          "Following": "फॉलोइंग",
          "Refer and Earn": "संदर्भ करें और कमाएं",
          "Directory": "निर्देशिका",
          "Help & Support": "सहायता और समर्थन",
          "FAQ's": "सामान्य प्रश्न",
          "Register as Astrologer": "ज्योतिषी के रूप में पंजीकरण करें",
          "Amount": "राशि",
          "Proceed to Pay": "भुगतान करने के लिए बढ़ें",
          "Subtotal": "उप-योग",
          "Total": "कुल",
          "Payment Successful": "सफल भुगतान ",
          "Wallet Balance": "वॉलेट शेष",
          "null": "null",
          "Aries": "मेष",
          "Taurus": "वृषभ",
          "Gemini": "मिथुन",
          "Cancer": "कर्क",
          "Leo": "सिंह",
          "Virgo": "कन्या",
          "Libra": "तुला",
          "Scorpio": "वृश्चिक",
          "Sagittarius": "धनु",
          "Capricorn": "मकर",
          "Aquarius": "कुंभ",
          "Pisces": "मीन",
          "Matchmaking": "दियासलाई बनाना",
          "Panchang": "पंचांग",
          "Gallery": "गैलरी",
          "Reviews": "समीक्षा",
          "Astrologer Profile": "ज्योतिषी प्रोफाइल",
          "Availability Time": "उपलब्धता समय",
          "Coupon": "कूपन",
          "Completed": "संपूरित",
          "All": "सब",
          "Ongoing": "चालू",
          "Consult": "परामर्श",
          "Time": "समय",
          "Duration": "अवधि",
          "Charge": "शुल्क",
          "Total Charge": "कुल शुल्क",
          "Follow": "फॉलो करे",
          "Total balance": "कुल शेष",
          "Recharge now": "रिचार्ज करें",
          "Wallet Transactions": "वॉलेट लेनदेन",
          "Payment Logs": "भुगतान लॉग",
          "Invoice": "बीजक",
          "Chat with \"Astrologer_Name\" for 10 mins":
              "ज्योतिषी से 10 मिनट तक चैट हुई",
          "Call with \"Astrologer_Name\" for 10 mins":
              "ज्योतिषी से 10 मिनट के लिए कॉल हुई",
          "Failed": "असफल",
          "Successful": "सफल",
          "Recharge": "रिचार्ज",
          "Transaction ID": "लेन-देन आईडी",
          "Hindi": "हिंदी",
          "Tamil": "तामिल",
          "Register yourself in Hello Astrologer Directory":
              "हेलो एस्ट्रोलॉजर निर्देशिका में खुद का पंजीकरण करें",
          "Click here": "क्लिक करें",
          "About Us": "हमारे बारे में",
          "privacy policy": "गोपनीयता नीति",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Log Out": "लॉग आउट",
          "Chat": "चैट",
          "Call": "कॉल",
          "Directory of Astro": "ज्योतिषी की निर्देशिका",
          "Home": "होम",
          "Settings": "सेटिंग",
          "Have doubts?": "संदेह है?",
          "Balance": "शेष",
          "Share": "शेयर"
        }
      };
}
